In [ ]:
%%timeit
[n*n for n in range(100)]

In [28]:
import numpy as np
np.__version__

'1.18.1'

# Basics of Numpy

In [ ]:
import numpy as np
a=np.array([1,2,3],dtype='int8') #initialise 1D arrray and set data type the value can be 16,8 but by default it is 32
b=np.array([[1.0,2.0,3.0],[3.0,5.0,0.0]]) #initialise 2D array, same way multidimensional array can be generated
print(a)
print(b)

In [ ]:
#get dimension of data
print(a.ndim)
print(b.ndim)

In [ ]:
#get shape
print(a.shape) 
print(b.shape) # 2 rows 3 column

In [ ]:
#get data type
print(a.dtype) # dtype=data type
print(b.dtype)

In [ ]:
#get size
print(a.size) #a.itemsize will give no. of element in array
print(b.size)
print(a.itemsize)# int8 give 1 size, int16 give 2 size, int32 give 4 size
print(b.itemsize)
print(a.nbytes) # no. of bytes samee as size of a


# accessing/changing specific elements row column etc.



In [ ]:
a=np.array([[1,2,3,4,5,6,7],[8,9 ,10,11,12,13,14]])  
a[0,:]  #array indexing starts from 0
a[1,2]  # to access element from first row 2 column
print(a[:,:])
# to access alternate element
a[1,1:-1:2]  # to print alternate element 
a[1,5]=20  # row 1 column 5 element changes to 20
print(a)
a[:,2]=[1,2]
print(a)


In [ ]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)
b[1,1,1]
#replace
b[1,0,0]=2
print(b)

## initializing different types of arrays

In [ ]:
#matrix with all 0
np.zeros((2,3),dtype='int16')
#matrix with all 1
np.ones((2,2))
#matrix with any other no.
np.full((2,2),5)
#matrix with diagonal 1s and other value 0
np.eye(4,4)



### generate matrix with random no.

In [ ]:
# random decimal number
np.random.rand(4,2) # generate random no. of size(4,2)
# random integer value
np.random.randint(6,size=(2,2)) #generate matrix of 2 row 2 col with random no. upto 5
np.random.randint(-2,8, size=(3,3))

In [ ]:
# identity matrix
np.identity(5)

In [ ]:
#repeat an array
a=np.array([1,2,3]) #1D array
b=np.repeat(a,3)
print(b)
c=np.array([[1,2,3]]) # 2D array
d=np.repeat(c,3,axis=0)
print(d)

In [ ]:
a=np.ones((5,5))
b=np.zeros((3,3))
a[1:-1,1:-1]=b
print(a)
a[2,2]=9
print(a)

### mathematics of array

In [ ]:
a=np.array([1,2,3,4],dtype='int16')
b=a+2
c=a-2
d=a/2
e=a*2
f=a**2
g=np.sin(a)
h=np.cos(a)
print(b,c,d,e,f,g,h)
#similarly we can do this with two arrays

### Linear Algebra

In [ ]:
#matrix multiplication
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=a*b
d=np.matmul(a,b)
e=np.ones((2,2))
f=np.zeros((2,2))
g=np.matmul(e,f)
print(c)
print(d)
print(g)

In [ ]:
#determinant of matrix
a=np.identity(3)
b=np.linalg.det(a)
print(b)

## Statistics

In [ ]:
a=np.array([[1,2,3],[4,5,6]])
np.sum(a) #give total sum of all the elements

In [ ]:
np.min(a,axis=0)

In [ ]:
np.max(a,axis=1) # max value of both rows

In [ ]:
np.sum(a,axis=0) #axis=0 : sum of column (vertical sum)

## reorganizing array

In [ ]:
# reshaping the array size
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)

b=a.reshape((4,2))
print(b)

In [ ]:
# vertical stacking and horizontally stacking
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.vstack([a,b,a,b,a,b])
print(c)

d=np.hstack((a,b))
print(d)

## load data

In [ ]:
filedata=np.genfromtxt('rak.txt',delimiter=',') #genfromtxt handles new line properly
print(filedata)
filedata.astype('int32')

In [ ]:
## boolean masking and advanced indexing
 # gives true or false for each value
filedata[filedata>10]


In [ ]:
np.any(filedata >5, axis=0)

In [ ]:
((filedata>5)&(filedata<10))

## Insert and flatten

In [ ]:
a=np.array([[1,2],[3,4],[5,6]])
print(a)
b=np.insert(a,0,1)  # syntax of insert= np.insert(array,obj,value,axis), where array= variable in which array is stored
                                                                               #obj= place in array where you want to insert, value=value you want to insert
print(b)
c=b.flatten()   # flatten function
print(c)

In [25]:
import numpy as np
X=np.array([[1,2,3,4,5],[6,7,8,9,10]],dtype='int8')
print(X)
ones=np.ones(len(X))
b=np.insert(X,0,ones,axis=1)
print(b)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  1  2  3  4  5]
 [ 1  6  7  8  9 10]]


In [32]:
%%Transpose of given matrix
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)
b=a.T  %T stands for transpose
print(b)

[[1 2 3 4]
 [5 6 7 8]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]
